

export default function ConceptualDocs() {

  return (
    <>
      <div className="col-span-3 overflow-y-auto">
        <div className="grid grid-cols-4 p-10">
          <div className="col-span-3">
            <div className="text-4xl font-extrabold mb-3">
              Conceptual Docs
            </div>
            <div className="text-[#94949c]">
              Learn the core concepts that make up NUX.
            </div>

            <div className="text-3xl font-extrabold mb-3 mt-16">
              Chain
            </div>
            <div className="text-[#94949c]">
              A chain defines a sequence of stages that are executed in order. Each stage performs a specific task such as searching, generating text, synthesizing audio etc. Chains allow automating workflows by chaining together multiple capabilities into an end-to-end process.
            </div>
            <div className="text-xl font-extrabold mb-3 mt-10">
              Key components of a chain
            </div>
            <div className="text-[#94949c]">
              <ul className="list-disc ml-4">
                <li><span className="text-white">Stages:</span> Each stage in the chain performs a discrete task. A stage has a type (e.g. search, text2text), configuration parameters, input, and output.</li>
                <li><span className="text-white">Execution Context:</span> The execution context contains data passed from one stage to the next. It allows stages to share information.</li>
                <li><span className="text-white">User Payload:</span> Optional input passed by the user when invoking the chain. Can override stage configurations.</li>
              </ul>
            </div>

            <div className="text-3xl font-extrabold mb-3 mt-16">
              Source
            </div>
            <div className="text-[#94949c]">
              A source represents an input data source like a file, website or database. Sources are parsed and indexed to enable search and other capabilities.
            </div>
            <div className="text-xl font-extrabold mb-3 mt-10">
              Key components of a source
            </div>
            <div className="text-[#94949c]">
              <ul className="list-disc ml-4">
                <li><span className="text-white">Source ID: </span>Unique identifier for the source.</li>
                <li><span className="text-white">Type: </span>Classification of source (file, website, etc).</li>
                <li><span className="text-white">Path: </span>Location of source (URL, file path etc).</li>
                <li><span className="text-white">Metadata: </span>Additional data about the source.</li>
                <li><span className="text-white">Contents: </span>Text content extracted from the source during parsing.</li>
                <li><span className="text-white">Embedding: </span>Numerical representation of the contents generated by a ML model.</li>
              </ul>
            </div>

            <div className="text-3xl font-extrabold mb-3 mt-16">
              Organization
            </div>
            <div className="text-[#94949c]">
              Organizations group users, indexes, sources, chains, and other resources.
            </div>
            <div className="text-xl font-extrabold mb-3 mt-10">
              Key components
            </div>
            <div className="text-[#94949c]">
              <ul className="list-disc ml-4">
                <li><span className="text-white">Org ID:</span> Unique identifier for the organization.</li>
                <li><span className="text-white">Users:</span> Member accounts belonging to the org.</li>
                <li><span className="text-white">Indexes:</span> Logical groupings of sources.</li>
                <li><span className="text-white">Chains:</span> Chains created under the organization.</li>
                <li><span className="text-white">API Keys:</span> Credentials used to authenticate requests.</li>
              </ul>
            </div>

            <div className="text-3xl font-extrabold mb-3 mt-16">
              MongoDB Integration
            </div>
            <div className="text-[#94949c]">
              The code integrates with a MongoDB database in the following ways:
            </div>
            <div className="text-xl font-extrabold mb-3 mt-10">
              Key integrations
            </div>
            <div className="text-[#94949c]">
              <ul className="list-disc ml-4">
                <li><span className="text-white">PyMongo Usage:</span> Uses PyMongo to connect to a MongoDB cluster and access collections like `organizations`, `sources` etc.</li>
                <li><span className="text-white">Document Storage:</span> Stores documents in MongoDB collections to persist entities like sources, chains, orgs etc.</li>
                <li><span className="text-white">Search Capabilities:</span> Uses MongoDB text search and vector similarity search for capabilities like search.</li>
                <li><span className="text-white">Atlas Search Indexes:</span> Can create Atlas Search indexes on embedding vectors to enable semantic search.</li>
                <li><span className="text-white">Aggregations in Chains:</span> Uses MongoDB aggregations in chain execution to implement multi-stage pipelines.</li>
              </ul>
            </div>
            <div className="text-[#94949c] mt-4">
              So MongoDB serves as the primary data store and execution engine for core capabilities.
            </div>

            <div className="text-3xl font-extrabold mb-3 mt-16">
              Supported ML Models
            </div>
            <div className="text-[#94949c]">
              The system currently supports the following ML models:
            </div>
            <div className="text-xl font-extrabold mb-3 mt-10">
              Model list
            </div>
            <div className="text-[#94949c]">
              <ul className="list-disc ml-4">
                <li><span className="text-white">SentenceTransformers:</span> For generating semantic text embeddings used in search.</li>
                <li><span className="text-white">OpenAI Whisper:</span> Speech to text transcription of audio.</li>
                <li><span className="text-white">OpenAI ChatGPT:</span> Text generation and summarization.</li>
                <li><span className="text-white">ElevenLabs:</span> Text to speech synthesis.</li>
              </ul>
            </div>
            <div className="text-[#94949c] mt-4">
              Additional models can be added by extending the relevant classes like `TextToText` or `FileEmbedder`.
            </div>



          </div>
          {/* <div className="col-span-1">
          <div>On this page</div>
        </div> */}
        </div>
      </div>
    </>
  );
}