import '../styles/globals.css'
import { Suspense } from 'react';
import type { Metadata } from 'next';

import { PHProvider, PostHogPageview } from './providers';

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nux Internal Docs',
  description: 'Generated by cluster',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Suspense>
        <PostHogPageview />
      </Suspense>
      <PHProvider>
        <body className={inter.className}>{children}</body>
      </PHProvider>
    </html>
  );
}
